plugins {
    id 'com.android.application'
}

android {
    namespace 'im.zego.aiagent.express.quickstart'
    compileSdk 34

    defaultConfig {
        applicationId "im.zego.aiagent.express.quickstart"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.5.1"
    implementation "com.google.android.material:material:1.6.1"
    implementation "androidx.constraintlayout:constraintlayout:2.1.4"

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "com.squareup.picasso:picasso:2.8"
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.3'
    implementation "com.google.code.gson:gson:2.9.1"

    implementation 'im.zego:zim:2.19.0'

    // 数字人 SDK
    implementation 'im.zego:digitalmobile:1.0.1.0'

    // 数字人 SDK 需要的第三方库
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'
    implementation "com.google.code.gson:gson:2.9.1"
    implementation 'com.liulishuo.okdownload:okdownload:1.0.7'
    implementation 'com.liulishuo.okdownload:sqlite:1.0.7'
    implementation 'com.liulishuo.okdownload:okhttp:1.0.7'
}